name: "security-sca-phylum"
run-name: SCA Scan for Dependencies

on: pull_request
jobs:
  analyze_deps:
    name: Analyze dependencies with Phylum
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    container:
      # This `slim` tag is smaller than the `latest` tag
      # but does not contain all the required tools for
      # lockfile generation. If that is desired, use the
      # `phylum-dev/phylum-analyze-pr-action` action instead.
      image: docker://ghcr.io/phylum-dev/phylum-ci:slim
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PHYLUM_API_KEY: ${{ secrets.PHYLUM_TOKEN }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Analyze dependencies
        run: phylum-ci -vv
