name: "security-sca-phylum"
run-name: SCA Scan for Dependencies

on: pull_request

jobs:
  analyze_deps:
    name: Analyze dependencies with Phylum
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Phylum Analyze PR
        uses: phylum-dev/phylum-analyze-pr-action@v2.2.0
        with: 
          phylum_token: $ {{ secrets.PHYLUM_TOKEN }}
          cmd: phylum-ci -vv
